<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Project.com');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Project" />
<meta name="keywords" content="Search Tutor" />
<?php echo $this->headMeta(); ?><?php echo $this->headTitle(); ?>
<?php echo $this->headLink() ?><?php echo $this->headStyle() ?>
<script type="text/javascript" src="/js/jquery-1.7.2.min.js"></script>
<?php echo $this->headScript() ?>

</head>
<body>





<?php echo $this->layout()->content; ?>



</body>
</html>
